# application-docker.yml
server:
  port: 8080

spring:
  application:
    name: sistema-notificacoes

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    connection-timeout: 30000
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2

logging:
  level:
    br.com.nt.sistema.notificacao: INFO
    org.springframework.amqp: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/notificacoes.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always