server:
  port: 8080

spring:
  application:
    name: sistema-notificacoes

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

logging:
  level:
    br.com.nt.sistema.notificacao: DEBUG
    org.springframework.amqp: DEBUG